name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger this pipeline on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger this pipeline on pull requests to the main branch

jobs:
  # Job to build the Docker image and test it
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      # Step 3: Log in to DockerHub (you can use GitHub's secrets to securely store your DockerHub credentials)
      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t vineetroy/pinecone-rag-groq-updated:latest .

      # Step 5: Push Docker image to DockerHub
      - name: Push Docker image to DockerHub
        run: |
          docker push vineetroy/pinecone-rag-groq-updated:latest

  # Job to deploy the Docker container
  deploy:
    runs-on: ubuntu-latest

    needs: build  # This job will run after the build job

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Pull Docker image from DockerHub
      - name: Pull Docker image
        run: |
          docker pull vineetroy/pinecone-rag-groq-updated:latest

      # Step 3: Run Docker container with secrets as environment variables
      - name: Run Docker container
        run: |
          docker run -d -p 8502:8501 \
          -e PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }} \
          -e GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} \
          vineetroy/pinecone-rag-groq-updated:latest
